# Generated by Django 3.2 on 2021-06-18 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date released')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='head/%Y')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banner/%Y')),
                ('is_banner', models.BooleanField(default=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('contents', models.CharField(max_length=3000)),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='news/%Y')),
            ],
        ),
    ]
